"""Editable starting lexicon for both variant-3 subject areas.

Rows are lemma, Penn POS (or *), German equivalent, domain.
The direct translation is deliberately inspectable and can be corrected in the UI.
"""

RAW = """
the|DT|der|general
a|DT|ein|general
an|DT|ein|general
this|DT|dieser|general
that|DT|jener|general
that|WDT|der|general
these|DT|diese|general
those|DT|jene|general
and|CC|und|general
or|CC|oder|general
but|CC|aber|general
of|IN|von|general
in|IN|in|general
on|IN|auf|general
at|IN|bei|general
to|TO|zu|general
to|IN|zu|general
for|IN|für|general
with|IN|mit|general
without|IN|ohne|general
from|IN|aus|general
by|IN|durch|general
as|IN|als|general
about|IN|über|general
between|IN|zwischen|general
after|IN|nach|general
before|IN|vor|general
under|IN|unter|general
over|IN|über|general
if|IN|wenn|general
because|IN|weil|general
although|IN|obwohl|general
while|IN|während|general
is|VBZ|ist|general
are|VBP|sind|general
am|VBP|bin|general
was|VBD|war|general
were|VBD|waren|general
be|VB|sein|general
been|VBN|gewesen|general
have|VBP|haben|general
has|VBZ|hat|general
had|VBD|hatte|general
do|VBP|tun|general
does|VBZ|tut|general
did|VBD|tat|general
can|MD|kann|general
could|MD|könnte|general
may|MD|kann|general
might|MD|könnte|general
must|MD|muss|general
should|MD|sollte|general
will|MD|wird|general
would|MD|würde|general
not|RB|nicht|general
very|RB|sehr|general
more|RBR|mehr|general
most|RBS|am meisten|general
also|RB|auch|general
only|RB|nur|general
often|RB|oft|general
however|RB|jedoch|general
therefore|RB|daher|general
it|PRP|es|general
they|PRP|sie|general
we|PRP|wir|general
he|PRP|er|general
she|PRP|sie|general
i|PRP|ich|general
you|PRP|du|general
their|PRP$|ihr|general
our|PRP$|unser|general
his|PRP$|sein|general
her|PRP$|ihr|general
my|PRP$|mein|general
which|WDT|welcher|general
who|WP|wer|general
what|WP|was|general
where|WRB|wo|general
when|WRB|wann|general
how|WRB|wie|general
new|JJ|neu|general
old|JJ|alt|general
good|JJ|gut|general
important|JJ|wichtig|general
different|JJ|verschieden|general
large|JJ|groß|general
small|JJ|klein|general
first|JJ|erste|general
other|JJ|andere|general
simple|JJ|einfach|general
many|JJ|viele|general
each|DT|jeder|general
all|DT|alle|general
one|CD|eins|general
two|CD|zwei|general
three|CD|drei|general
use|VB|verwenden|general
used|VBN|verwendet|general
uses|VBZ|verwendet|general
show|VB|zeigen|general
shows|VBZ|zeigt|general
make|VB|machen|general
makes|VBZ|macht|general
made|VBD|machte|general
provide|VB|bereitstellen|general
provides|VBZ|stellt bereit|general
include|VB|umfassen|general
includes|VBZ|umfasst|general
contain|VB|enthalten|general
contains|VBZ|enthält|general
result|NN|Ergebnis|general
results|NNS|Ergebnisse|general
method|NN|Methode|general
methods|NNS|Methoden|general
analysis|NN|Analyse|general
example|NN|Beispiel|general
examples|NNS|Beispiele|general
study|NN|Studie|general
studies|NNS|Studien|general
research|NN|Forschung|general
researchers|NNS|Forscher|general
paper|NN|Artikel|general
article|NN|Artikel|general
work|NN|Arbeit|general
problem|NN|Problem|general
solution|NN|Lösung|general
system|NN|System|computer_science
systems|NNS|Systeme|computer_science
computer|NN|Computer|computer_science
science|NN|Wissenschaft|computer_science
computer science|*|Informatik|computer_science
software|NN|Software|computer_science
hardware|NN|Hardware|computer_science
program|NN|Programm|computer_science
programs|NNS|Programme|computer_science
programming|NN|Programmierung|computer_science
code|NN|Code|computer_science
source code|*|Quellcode|computer_science
data|NNS|Daten|computer_science
database|NN|Datenbank|computer_science
databases|NNS|Datenbanken|computer_science
table|NN|Tabelle|computer_science
query|NN|Abfrage|computer_science
queries|NNS|Abfragen|computer_science
algorithm|NN|Algorithmus|computer_science
algorithms|NNS|Algorithmen|computer_science
model|NN|Modell|computer_science
models|NNS|Modelle|computer_science
network|NN|Netzwerk|computer_science
neural network|*|neuronales Netzwerk|computer_science
neural networks|*|neuronale Netzwerke|computer_science
machine learning|*|maschinelles Lernen|computer_science
artificial intelligence|*|künstliche Intelligenz|computer_science
natural language processing|*|Verarbeitung natürlicher Sprache|computer_science
learning|NN|Lernen|computer_science
training|NN|Training|computer_science
prediction|NN|Vorhersage|computer_science
classification|NN|Klassifikation|computer_science
classifier|NN|Klassifikator|computer_science
feature|NN|Merkmal|computer_science
features|NNS|Merkmale|computer_science
input|NN|Eingabe|computer_science
output|NN|Ausgabe|computer_science
performance|NN|Leistung|computer_science
measures|NNS|Maße|computer_science
accuracy|NN|Genauigkeit|computer_science
efficiency|NN|Effizienz|computer_science
optimization|NN|Optimierung|computer_science
architecture|NN|Architektur|computer_science
interface|NN|Schnittstelle|computer_science
user|NN|Benutzer|computer_science
users|NNS|Benutzer|computer_science
application|NN|Anwendung|computer_science
applications|NNS|Anwendungen|computer_science
web|NN|Web|computer_science
server|NN|Server|computer_science
client|NN|Client|computer_science
file|NN|Datei|computer_science
files|NNS|Dateien|computer_science
document|NN|Dokument|computer_science
documents|NNS|Dokumente|computer_science
text|NN|Text|computer_science
token|NN|Token|computer_science
tokens|NNS|Token|computer_science
language|NN|Sprache|computer_science
translation|NN|Übersetzung|computer_science
translate|VB|übersetzen|computer_science
translated|VBN|übersetzt|computer_science
process|NN|Prozess|computer_science
process|VB|verarbeiten|computer_science
processes|VBZ|verarbeitet|computer_science
processing|NN|Verarbeitung|computer_science
natural|JJ|natürlich|computer_science
neural|JJ|neuronal|computer_science
machine|NN|Maschine|computer_science
artificial|JJ|künstlich|computer_science
intelligence|NN|Intelligenz|computer_science
store|VB|speichern|computer_science
stores|VBZ|speichert|computer_science
stored|VBN|gespeichert|computer_science
compute|VB|berechnen|computer_science
computes|VBZ|berechnet|computer_science
improve|VB|verbessern|computer_science
improves|VBZ|verbessert|computer_science
improved|JJ|verbessert|computer_science
show|VBP|zeigen|general
describes|VBZ|beschreibt|general
develop|VB|entwickeln|computer_science
developed|VBN|entwickelt|computer_science
design|NN|Entwurf|computer_science
designed|VBN|entworfen|computer_science
evaluate|VB|bewerten|computer_science
evaluated|VBN|bewertet|computer_science
novel|NN|Roman|literature
novels|NNS|Romane|literature
story|NN|Geschichte|literature
stories|NNS|Geschichten|literature
poem|NN|Gedicht|literature
poems|NNS|Gedichte|literature
poetry|NN|Poesie|literature
literature|NN|Literatur|literature
literary|JJ|literarisch|literature
author|NN|Autor|literature
authors|NNS|Autoren|literature
writer|NN|Schriftsteller|literature
young|JJ|jung|literature
town|NN|Stadt|literature
reader|NN|Leser|literature
readers|NNS|Leser|literature
character|NN|Figur|literature
characters|NNS|Figuren|literature
protagonist|NN|Protagonist|literature
narrator|NN|Erzähler|literature
plot|NN|Handlung|literature
theme|NN|Thema|literature
themes|NNS|Themen|literature
symbol|NN|Symbol|literature
symbols|NNS|Symbole|literature
metaphor|NN|Metapher|literature
imagery|NN|Bildsprache|literature
setting|NN|Schauplatz|literature
chapter|NN|Kapitel|literature
ending|NN|Ende|literature
second|JJ|zweite|literature
beginning|NN|Anfang|literature
conflict|NN|Konflikt|literature
dialogue|NN|Dialog|literature
voice|NN|Stimme|literature
style|NN|Stil|literature
tone|NN|Ton|literature
perspective|NN|Perspektive|literature
meaning|NN|Bedeutung|literature
interpretation|NN|Interpretation|literature
criticism|NN|Kritik|literature
essay|NN|Aufsatz|literature
essays|NNS|Aufsätze|literature
describe|VB|beschreiben|literature
describes|VBZ|beschreibt|literature
portray|VB|darstellen|literature
portrays|VBZ|stellt dar|literature
write|VB|schreiben|literature
writes|VBZ|schreibt|literature
wrote|VBD|schrieb|literature
written|VBN|geschrieben|literature
read|VB|lesen|literature
reads|VBZ|liest|literature
said|VBD|sagte|literature
says|VBZ|sagt|literature
tells|VBZ|erzählt|literature
lives|VBZ|lebt|literature
begins|VBZ|beginnt|literature
gives|VBZ|gibt|literature
examines|VBZ|untersucht|literature
hope|NN|Hoffnung|literature
love|NN|Liebe|literature
death|NN|Tod|literature
life|NN|Leben|literature
time|NN|Zeit|literature
world|NN|Welt|literature
society|NN|Gesellschaft|literature
human|JJ|menschlich|literature
dark|JJ|dunkel|literature
beautiful|JJ|schön|literature
complex|JJ|komplex|literature
tragic|JJ|tragisch|literature
"""


def seed_rows():
    for raw in RAW.strip().splitlines():
        english, pos, german, domain = raw.split("|")
        yield english, pos, german, domain
